# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_to_client_pb2 as server__to__client__pb2


class NapsterServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPeer = channel.unary_unary(
                '/NapsterServer/RegisterPeer',
                request_serializer=server__to__client__pb2.RegisterPeerRequest.SerializeToString,
                response_deserializer=server__to__client__pb2.RegisterPeerResponse.FromString,
                )
        self.GetPeersServingRequestedFile = channel.unary_unary(
                '/NapsterServer/GetPeersServingRequestedFile',
                request_serializer=server__to__client__pb2.FileRequest.SerializeToString,
                response_deserializer=server__to__client__pb2.FileResponse.FromString,
                )


class NapsterServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterPeer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeersServingRequestedFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NapsterServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPeer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPeer,
                    request_deserializer=server__to__client__pb2.RegisterPeerRequest.FromString,
                    response_serializer=server__to__client__pb2.RegisterPeerResponse.SerializeToString,
            ),
            'GetPeersServingRequestedFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeersServingRequestedFile,
                    request_deserializer=server__to__client__pb2.FileRequest.FromString,
                    response_serializer=server__to__client__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NapsterServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NapsterServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterPeer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NapsterServer/RegisterPeer',
            server__to__client__pb2.RegisterPeerRequest.SerializeToString,
            server__to__client__pb2.RegisterPeerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPeersServingRequestedFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NapsterServer/GetPeersServingRequestedFile',
            server__to__client__pb2.FileRequest.SerializeToString,
            server__to__client__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
